/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { GasRefund } from "./GasRefund";

export class GasRefundFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): GasRefund {
    return new Contract(address, _abi, signerOrProvider) as GasRefund;
  }
}

const _abi = [
  {
    inputs: [],
    name: "remainingGasRefundPool",
    outputs: [
      {
        internalType: "uint256",
        name: "length",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "remainingSheepRefundPool",
    outputs: [
      {
        internalType: "uint256",
        name: "length",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];
