/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface ICurveInterface extends ethers.utils.Interface {
  functions: {
    "calc_token_amount(uint256[4],bool)": FunctionFragment;
    "get_virtual_price()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "calc_token_amount",
    values: [[BigNumberish, BigNumberish, BigNumberish, BigNumberish], boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "get_virtual_price",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "calc_token_amount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "get_virtual_price",
    data: BytesLike
  ): Result;

  events: {};
}

export class ICurve extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: ICurveInterface;

  functions: {
    calc_token_amount(
      amounts: [BigNumberish, BigNumberish, BigNumberish, BigNumberish],
      deposit: boolean,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "calc_token_amount(uint256[4],bool)"(
      amounts: [BigNumberish, BigNumberish, BigNumberish, BigNumberish],
      deposit: boolean,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    get_virtual_price(
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "get_virtual_price()"(
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;
  };

  calc_token_amount(
    amounts: [BigNumberish, BigNumberish, BigNumberish, BigNumberish],
    deposit: boolean,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "calc_token_amount(uint256[4],bool)"(
    amounts: [BigNumberish, BigNumberish, BigNumberish, BigNumberish],
    deposit: boolean,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  get_virtual_price(overrides?: CallOverrides): Promise<BigNumber>;

  "get_virtual_price()"(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    calc_token_amount(
      amounts: [BigNumberish, BigNumberish, BigNumberish, BigNumberish],
      deposit: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "calc_token_amount(uint256[4],bool)"(
      amounts: [BigNumberish, BigNumberish, BigNumberish, BigNumberish],
      deposit: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    get_virtual_price(overrides?: CallOverrides): Promise<BigNumber>;

    "get_virtual_price()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    calc_token_amount(
      amounts: [BigNumberish, BigNumberish, BigNumberish, BigNumberish],
      deposit: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "calc_token_amount(uint256[4],bool)"(
      amounts: [BigNumberish, BigNumberish, BigNumberish, BigNumberish],
      deposit: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    get_virtual_price(overrides?: CallOverrides): Promise<BigNumber>;

    "get_virtual_price()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    calc_token_amount(
      amounts: [BigNumberish, BigNumberish, BigNumberish, BigNumberish],
      deposit: boolean,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "calc_token_amount(uint256[4],bool)"(
      amounts: [BigNumberish, BigNumberish, BigNumberish, BigNumberish],
      deposit: boolean,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    get_virtual_price(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "get_virtual_price()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
