/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface MockHookInterface extends ethers.utils.Interface {
  functions: {
    "hook()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "hook", values?: undefined): string;

  decodeFunctionResult(functionFragment: "hook", data: BytesLike): Result;

  events: {};
}

export class MockHook extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: MockHookInterface;

  functions: {
    hook(overrides?: Overrides): Promise<ContractTransaction>;

    "hook()"(overrides?: Overrides): Promise<ContractTransaction>;
  };

  hook(overrides?: Overrides): Promise<ContractTransaction>;

  "hook()"(overrides?: Overrides): Promise<ContractTransaction>;

  callStatic: {
    hook(overrides?: CallOverrides): Promise<void>;

    "hook()"(overrides?: CallOverrides): Promise<void>;
  };

  filters: {};

  estimateGas: {
    hook(overrides?: Overrides): Promise<BigNumber>;

    "hook()"(overrides?: Overrides): Promise<BigNumber>;
  };

  populateTransaction: {
    hook(overrides?: Overrides): Promise<PopulatedTransaction>;

    "hook()"(overrides?: Overrides): Promise<PopulatedTransaction>;
  };
}
